### ISSUE TITLE
Can't install using the package manager on ubuntu 16.04

### ISSUE THREAD

**Issue by glassman3d** [joeroback/atom-clang#23]
I am unable to isntall this on ubuntu-16.0.4
have installed llvm-3.8, npm and node.js as instructed in teh error 

> segfault-handler@1.0.0 install /tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory '/tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang/node_modules/segfault-handler/build'

> atom-clang@1.0.14 install /tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang/build'
  CXX(target) Release/obj.target/clang/src/clang_translationunit.o
clang.target.mk:122: recipe for target 'Release/obj.target/clang/src/clang_translationunit.o' failed
make: Leaving directory '/tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang/build'

In file included from ../src/clang_translationunit.cpp:9:0:
../src/clang_helpers.hpp:8:27: fatal error: clang-c/Index.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/clang/src/clang_translationunit.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11715-20784-1o4k8n5/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11715-20784-1o4k8n5/package.json'
npm WARN apm-install-dir-11715-20784-1o4k8n5 No description
npm WARN apm-install-dir-11715-20784-1o4k8n5 No repository field.
npm WARN apm-install-dir-11715-20784-1o4k8n5 No README data
npm WARN apm-install-dir-11715-20784-1o4k8n5 No license field.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/sam/.atom/.apm/.apmrc" "--userconfig" "/home/sam/.atom/.apmrc" "install" "/tmp/d-11715-20784-122662n/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11715-20784-1o4k8n5/npm-debug.lo

**Comment by joeroback** [comment]
`../src/clang_helpers.hpp:8:27: fatal error: clang-c/Index.h: No such file or directory` tells me that you do not have llvm installed correctly or atom cannot find the `llvm-config` executable. How did you install LLVM? APT or tar.gz or build it from source?

Can you execute `llvm-config --includedir` on the command line and get any output? For example, on my Macbook

```
$ llvm-config --includedir
/opt/local/libexec/llvm-3.9/include
```

**Comment by glassman3d** [comment]
Hi Joe

Thanks for the quick reply!
As you suggested I did not have llvm installed correctly, I fixed this as
seen below

llvm-config --includedir
/usr/lib/llvm-3.8/include

unfortunately this has not fixed the installation - my latest error:



> segfault-handler@1.0.0 install /tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

make: Entering directory
'/tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang/node_modules/segfault-handler/build'
  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/obj.target/segfault-handler.node
  COPY Release/segfault-handler.node
make: Leaving directory
'/tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang/node_modules/segfault-handler/build'

> atom-clang@1.0.14 install /tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang
> node-gyp rebuild

make: Entering directory
'/tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang/build'
  CXX(target) Release/obj.target/clang/src/clang_translationunit.oclang.target.mk:122:
recipe for target
'Release/obj.target/clang/src/clang_translationunit.o' failed
make: Leaving directory
'/tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang/build'

In file included from ../src/clang_translationunit.cpp:9:0:
../src/clang_helpers.hpp:8:27: fatal error: clang-c/Index.h: No such
file or directory
compilation terminated.
make: *** [Release/obj.target/clang/src/clang_translationunit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/opt/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node"
"/opt/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11715-30387-ecfh5n/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open
'/tmp/apm-install-dir-11715-30387-ecfh5n/package.json'
npm WARN apm-install-dir-11715-30387-ecfh5n No description
npm WARN apm-install-dir-11715-30387-ecfh5n No repository field.
npm WARN apm-install-dir-11715-30387-ecfh5n No README data
npm WARN apm-install-dir-11715-30387-ecfh5n No license field.
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node"
"/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js"
"--globalconfig" "/home/sam/.atom/.apm/.apmrc" "--userconfig"
"/home/sam/.atom/.apmrc" "install"
"/tmp/d-11715-30387-1cxcbox/package.tgz" "--runtime=electron"
"--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-ins

**Comment by joeroback** [comment]
atom is still not able to find llvm... I have a VM with 16.04 on can try. Can you please let me know how you installed LLVM so I can replicate? APT? Source? Binary tar.gz from LLVM.org? Thanks.

**Comment by glassman3d** [comment]
hi joe I ran sudo apt install llvm

**Comment by joeroback** [comment]
if you are installing from the ubuntu repositories, i think you need the package `libclang-3.8-dev`

**Comment by joeroback** [comment]
so on my VM fresh `UbuntuGnome 16.04` install using `Atom 1.13.1`, I had to apt-get these
```
apt-get install zlib1g-dev g++ libclang-3.8-dev llvm-3.8-dev
```
![image](https://cloud.githubusercontent.com/assets/156174/22676128/e74b54fc-eca6-11e6-9ad9-0716293d96ed.png)

I'll update the docs on my next feature push. Thanks for the report.

**Comment by glassman3d** [comment]
great thanks I will give that a go this eve

**Comment by glassman3d** [comment]
many thanks - all installed!
