### ISSUE TITLE
Add support for cmake

### ISSUE THREAD

**Issue by xphoenix** [joeroback/atom-clang#24]
It is possible to generate compile commands database with cmake from which it is possible to get exact arguments for clang compile: https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html

**Comment by joeroback** [comment]
this is in the works for support for .clang_complete files, it will be in the next release. There are some caveats though, as compile_commands.json does not contain header files, so for header-only sources, like in some C++ projects, its unclear which flags to use. Also headers can vary as to which flags are applied to them based on which translation unit is being compiled, but generally projects are not that complex.

trying not to delay the release too much, but also trying not to release a trainwreck either. Soon, maybe March timeframe.

**Comment by joeroback** [comment]
issue #8  is the other enhancement for clang_complete support.

**Comment by xphoenix** [comment]
Run through #8 - closing this one as an obvious duplicate
