### ISSUE TITLE
Cannot install using package manager on MacOSX 10.12.3

### ISSUE THREAD

**Issue by TheChurro** [joeroback/atom-clang#26]
This is a very similar issue to #23 . I am unable to install on MacOSX Sierra 10.12.3. 

Having installed llvm with homebrew I receive the error

`> segfault-handler@1.0.0 install /private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/apm-install-dir-117212-4035-1w064o8/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node

> atom-clang@1.0.14 install /private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/apm-install-dir-117212-4035-1w064o8/node_modules/atom-clang
> node-gyp rebuild

  CXX(target) Release/obj.target/clang/src/clang_translationunit.o

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
In file included from ../src/clang_translationunit.cpp:4:
/usr/local/Cellar/llvm@3.8/3.8.1/lib/llvm-3.8/bin/../include/c++/v1/cassert:21:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^
1 error generated.
make: *** [Release/obj.target/clang/src/clang_translationunit.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/apm-install-dir-117212-4035-1w064o8/node_modules/atom-clang
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/apm-install-dir-117212-4035-1w064o8/package.json'
npm WARN apm-install-dir-117212-4035-1w064o8 No description
npm WARN apm-install-dir-117212-4035-1w064o8 No repository field.
npm WARN apm-install-dir-117212-4035-1w064o8 No README data
npm WARN apm-install-dir-117212-4035-1w064o8 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/johnchuray/.atom/.apm/.apmrc" "--userconfig" "/Users/johnchuray/.atom/.apmrc" "install" "/private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/d-117212-4035-114pwqi/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/s6/9v8y_7w97fzg4vzgsmqtwp780000gn/T/apm-install-dir-117212-4035-1w064o8/npm-debug.log`

I have attempted installation with both llvm3.9 and llvm3.8. Running llvm-config gives the following
`llvm-config --includedir
/usr/local/Cellar/llvm@3.8/3.8.1/lib/llvm-3.8/include`

I have updated node.js and npm and am running the latest version of atom.

**Comment by joeroback** [comment]
nodejs and npm do not matter in this case, as Atom provides an internal nodejs and apm not npm.

It is having a problem finding "assert.h" which is system header, usually shipped with the compiler or with the system (ie command line tools on osx).

this is weird, but node-gyp is terrible build tool (chrome has recently deprecated it only to replace it with more garbage, unfortunately). The next release, hopefully out soon will use the cmake-js package to use CMake for figuring out build tools and dependencies, so hopefully it will greatly reduce these sorts of build issues.

For now, the only thing I can suggest is, try and find assert.h on your system. On my OS X system running 10.12.3 it is located here:
```
$ ll -lsad /usr/include/assert.h         
0 -r--r--r--  1 root  wheel   4.1K Oct  5 17:00 /usr/include/assert.h
$ uname -a
Darwin bender.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

**Comment by TheChurro** [comment]
Hello thank you for the help. My computer is new and it turns out that I forgot to install the xcode command line tools and once I did that everything linked properly. Thank you for the help.
