### ISSUE TITLE
atom-clang

### ISSUE THREAD

**Issue by zeljkobilbija** [joeroback/atom-clang#29]
Packages are published to atom.io and are installed to /Users/zeljkobilbija/.atom/packages

  
c code comletition
PackagesThemes
Installing “atom-clang@1.0.14” failed.Hide output…

> segfault-handler@1.0.0 install /private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/apm-install-dir-117328-3444-avh7uf.rcteqgds4i/node_modules/atom-clang/node_modules/segfault-handler
> node-gyp rebuild

  CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
  SOLINK_MODULE(target) Release/segfault-handler.node

> atom-clang@1.0.14 install /private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/apm-install-dir-117328-3444-avh7uf.rcteqgds4i/node_modules/atom-clang
> node-gyp rebuild

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
/bin/sh: --: invalid option
Usage:	/bin/sh [GNU long option] [option] ...
	/bin/sh [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
gyp: Call to '--includedir' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/apm-install-dir-117328-3444-avh7uf.rcteqgds4i/node_modules/atom-clang
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/apm-install-dir-117328-3444-avh7uf.rcteqgds4i/package.json'
npm WARN apm-install-dir-117328-3444-avh7uf.rcteqgds4i No description
npm WARN apm-install-dir-117328-3444-avh7uf.rcteqgds4i No repository field.
npm WARN apm-install-dir-117328-3444-avh7uf.rcteqgds4i No README data
npm WARN apm-install-dir-117328-3444-avh7uf.rcteqgds4i No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/zeljkobilbija/.atom/.apm/.apmrc" "--userconfig" "/Users/zeljkobilbija/.atom/.apmrc" "install" "/private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/d-117328-3444-10b5fo9.s8y83t0529/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-clang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/d2/wsqzzt216sl99xplk138vpy40000gn/T/apm-install-dir-117328-3444-avh7uf.rcteqgds4i/npm-debug.log

**Comment by joeroback** [comment]
you don't have llvm installed. needs to find `llvm-config` command, either the Apple Command Line Tools one or from MacPorts, Homebrew, etc.

**Comment by zeljkobilbija** [comment]
Thank You.
