### ISSUE TITLE
Linter: Ignore diagnostics outside of the workspace directories?

### ISSUE THREAD

**Issue by joeroback** [joeroback/atom-clang#3]
For example, ignore warnings/errors from included boost libs?  This really comes up with std::forward / aka emplace... Unsure if there is a good way to exclude these and still have it work with emplace..

**Comment by janosimas** [comment]
When you link a lib you can say it a system lib (g++ and clang), this way they ignore the warnings.
Unless you want to parse and modify the compile command I'm not sure you can do that.

**Comment by joeroback** [comment]
you mean when you add a library include path? yea, -isystem should do that. and that reminds me, when i filed this, i was using -I to include my boost headers, after i switched to -isystem in my CXXFLAGS it went away :)
