### ISSUE TITLE
fails to load after libclang update

### ISSUE THREAD

**Issue by Glavnokoman** [joeroback/atom-clang#30]
first installed atom-clang with libclang 3.9. After upgrade to 4.0 does not work any more even after plugin recompile.

**Comment by joeroback** [comment]
not enough information... what do you mean does not work? Does not perform completions? Crashes? Throws errors to the console log?

For example, looking at the console, I see clang 4.0.0 using the clang binaries tar.gz from llvm.org on ubuntu 14.04

![atom-clang-4](https://cloud.githubusercontent.com/assets/156174/26319471/62b9274a-3edc-11e7-84cd-b8b1da3223ed.png)

Do you at least see that?

**Comment by Glavnokoman** [comment]
sorry not being specific enough. clang 4.0 is not a problem by itself, I
have it now working with it. The problem was that after updating clang the
makefiles were still pointing to old library. So when I rebuilt the
atom-clang it failed to load with a message (out of memory)
"libclang.so.3.9 could not be found"
