### ISSUE TITLE
cannot install on osx

### ISSUE THREAD

**Issue by tigranavanesov** [joeroback/atom-clang#33]
**MacOS Sierra 10.12.6 (16G29)**
**Atom version 1.20.1 x64**

> Installing “atom-clang@1.0.14” failed.Hide output…
> 
> > segfault-handler@1.0.0 install /private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/apm-install-dir-117828-71544-rgdr9a.1imkne9udi/node_modules/atom-clang/node_modules/segfault-handler
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/segfault-handler/src/segfault-handler.o
>   SOLINK_MODULE(target) Release/segfault-handler.node
> 
> > atom-clang@1.0.14 install /private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/apm-install-dir-117828-71544-rgdr9a.1imkne9udi/node_modules/atom-clang
> > node-gyp rebuild
> 
> 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
> 
> /bin/sh: --: invalid option
> Usage:	/bin/sh [GNU long option] [option] ...
> 	/bin/sh [GNU long option] [option] script-file ...
> GNU long options:
> 	--debug
> 	--debugger
> 	--dump-po-strings
> 	--dump-strings
> 	--help
> 	--init-file
> 	--login
> 	--noediting
> 	--noprofile
> 	--norc
> 	--posix
> 	--protected
> 	--rcfile
> 	--restricted
> 	--verbose
> 	--version
> 	--wordexp
> Shell options:
> 	-irsD or -c command or -O shopt_option		(invocation only)
> 	-abefhkmnptuvxBCHP or -o option
> gyp: Call to '--includedir' returned exit status 2 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:305:16)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Darwin 16.7.0
> gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
> gyp ERR! cwd /private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/apm-install-dir-117828-71544-rgdr9a.1imkne9udi/node_modules/atom-clang
> gyp ERR! node -v v6.9.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/apm-install-dir-117828-71544-rgdr9a.1imkne9udi/package.json'
> npm WARN apm-install-dir-117828-71544-rgdr9a.1imkne9udi No description
> npm WARN apm-install-dir-117828-71544-rgdr9a.1imkne9udi No repository field.
> npm WARN apm-install-dir-117828-71544-rgdr9a.1imkne9udi No README data
> npm WARN apm-install-dir-117828-71544-rgdr9a.1imkne9udi No license field.
> npm ERR! Darwin 16.7.0
> npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/tigran/.atom/.apm/.apmrc" "--userconfig" "/Users/tigran/.atom/.apmrc" "install" "/private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/d-117828-71544-69jenf.dsou0x80k9/package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-clang@1.0.14 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-clang@1.0.14 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-clang package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-clang
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-clang
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /private/var/folders/d2/crwsn8194914y9l1_phph8xr0000gn/T/apm-install-dir-117828-71544-rgdr9a.1imkne9udi/npm-debug.log
>

**Comment by joeroback** [comment]
atom-clang cannot find LLVM/Clang on your system. You either need to install Xcode + Command Line Developer tools or install Clang via brew/MacPorts and make sure `llvm-config` is in your environment's path.

**Comment by joeroback** [comment]
but basically the build script, which needs to build and link against libclang, is failing to find the executable `llvm-config` on your system.

**Comment by JerrySievert** [comment]
I have `LLVM_CONFIG` set correctly for macOS in the environment for `fish` and `bash`, and it's still looking in `/usr/bin/clangd`, it tells me I need to set it correctly in the package config - is there a package config that I can actually set to make this work?

thanks!

**Comment by joeroback** [comment]
if you are just setting LLVM_CONFIG in your .bashrc, then macOS GUI applications will not have it set.. macOS environment variables do not work that way.. you need to set them in launchd.conf or something like that. Its stupid, but so is macOS.

**Comment by csiszarattila** [comment]
Same error here.
Installing llvm through homebrew and adding llvm bin dir to the PATH 

`export PATH="/usr/local/opt/llvm/bin:$PATH"`

solved the problem.

**Comment by joeroback** [comment]
ok i pushed a fix to support clang 5.0 and clang 6.0

Xcode does not ship with the libclang headers, only the library, so you have to install clang/llvm from MacPorts or Homebrew and `llvm-config` (or `llvm-config-mp-6.0` for example with MacPorts) needs to be installed and in `bash` `PATH`.

**Comment by joeroback** [comment]
closing, feel free to re-open if it still does not work for you
