### ISSUE TITLE
Unable to specify include folders

### ISSUE THREAD

**Issue by IssamT** [joeroback/atom-clang#34]
I am using mac os sierra, and I am unable to specify the include folder of my project. (Include files are only recognized by other include files which are in the same folder)

I have tried to do it in different ways, but none of them worked.

- Modifying $MYPROJECT/project.cson (as shown in the readme example)
- Doing the same on $HOME/.atom/projects.cson
- `export CXXFLAGS="- I /path/to/include" ; open /Applications/Atom.app`
- `export CPPFLAGS="- I /path/to/include" ; open /Applications/Atom.app`

**Comment by IssamT** [comment]
Specifying CXXFLAGS in the package setting worked (it's global but I m ok with it).

**Comment by joeroback** [comment]
yea, project manager package for atom will just you set per project config settings.. other than that, i think atom still missing such support

working on clang_complete support, compile_commands.json support as we speak, which will hopefully be better than using the atom config system..
