### ISSUE TITLE
Show function signature after insertion

### ISSUE THREAD

**Issue by bartosz-m** [joeroback/atom-clang#39]
Would it be possible to display somewhere function signature after it was selected from autocompletion?
Right now I need to remember all parameter and this is no go when working with unfamiliar stuff e.g. "Unreal Engine" 
![](https://raw.githubusercontent.com/bartosz-m/ue4-tools/master/doc/images/screenshot.gif)

Description of method are tremendously helpful but after I select function/method there is no hint about arguments. I really would like to replace vscode with atom for UE4 development but right now it would be to painful.

By the way thank for great package! it can flawlessly parse UE4 project - a feet that no other package could do.

**Comment by joeroback** [comment]
ironically i have replaced atom with vscode for my c++ development... this plugin uses libclang directly and all things, including atom, are going down the route of Language Server Protocol and with clang officially supporting their own LSP server, `clangd` I have not worked on this plugin in a long time...

**Comment by bartosz-m** [comment]
thanks for info. It looks like I'll need stick to vscode.
