### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by j-griffith** [joeroback/atom-clang#4]
I haven't dug into this at all but will when I find some time.  Meanwhile, error info below...

 
Installing “atom-clang@1.0.1” failed.Hide output…

> atom-clang@1.0.1 install /private/var/folders/3d/vjvbzxq963b_x2bjh2lqbl2h0000gn/T/apm-install-dir-116725-2271-7s44lf/node_modules/atom-clang
> node-gyp rebuild

/bin/sh: llvm-config: command not found
gyp: Call to 'llvm-config --includedir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/3d/vjvbzxq963b_x2bjh2lqbl2h0000gn/T/apm-install-dir-116725-2271-7s44lf/node_modules/atom-clang
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jgriffith/.atom/.apm/.apmrc" "--userconfig" "/Users/jgriffith/.atom/.apmrc" "install" "/private/var/folders/3d/vjvbzxq963b_x2bjh2lqbl2h0000gn/T/d-116725-2271-16b1pt3/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-clang@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-clang@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the atom-clang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-clang
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/3d/vjvbzxq963b_x2bjh2lqbl2h0000gn/T/apm-install-dir-116725-2271-7s44lf/npm-debug.log

**Comment by joeroback** [comment]
you need to have clang-3.8 or greater installed. See README.md 🎱
