### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Danilodum** [joeroback/atom-clang#5]
Hi, could you help me with the followin error?

> > atom-clang@1.0.1 install /tmp/apm-install-dir-116726-7339-1co0db9.3grqdoyldi/node_modules/atom-clang
> > node-gyp rebuild
> 
> make: Entering directory '/tmp/apm-install-dir-116726-7339-1co0db9.3grqdoyldi/node_modules/atom-clang/build'
>   CXX(target) Release/obj.target/clang/src/clang_translationunit.o
> make: Leaving directory '/tmp/apm-install-dir-116726-7339-1co0db9.3grqdoyldi/node_modules/atom-clang/build'
> 
> ../src/clang_translationunit.cpp: In member function ‘int node_clang::clang_translationunit::parse(bool, node_clang::command_line_args&, node_clang::unsaved_files&, std::vector<node_clang::diagnostic>&)’:
> ../src/clang_translationunit.cpp:334:32: error: ‘CXTranslationUnit_CreatePreambleOnFirstParse’ was not declared in this scope
>                                 CXTranslationUnit_CreatePreambleOnFirstParse |
>                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make: *** [clang.target.mk:112: Release/obj.target/clang/src/clang_translationunit.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Linux 4.7.2-1-ARCH
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /tmp/apm-install-dir-116726-7339-1co0db9.3grqdoyldi/node_modules/atom-clang
> gyp ERR! node -v v6.4.0
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-116726-7339-1co0db9.3grqdoyldi/package.json'
> npm WARN apm-install-dir-116726-7339-1co0db9.3grqdoyldi No description
> npm WARN apm-install-dir-116726-7339-1co0db9.3grqdoyldi No repository field.
> npm WARN apm-install-dir-116726-7339-1co0db9.3grqdoyldi No README data
> npm WARN apm-install-dir-116726-7339-1co0db9.3grqdoyldi No license field.
> npm ERR! Linux 4.7.2-1-ARCH
> npm ERR! argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/snazilo/.atom/.apm/.apmrc" "--userconfig" "/home/snazilo/.atom/.apmrc" "install" "/tmp/d-116726-7339-vsmcpi.7ptew5ewmi/package.tgz" "--runtime=electron" "--target=1.3.4" "--arch=x64" "--global-style"
> npm ERR! node v6.4.0
> npm ERR! npm  v3.10.6
> npm ERR! code ELIFECYCLE
> 
> npm ERR! atom-clang@1.0.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the atom-clang@1.0.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the atom-clang package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs atom-clang
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls atom-clang
> npm ERR! There is likely additional logging output above.

**Comment by joeroback** [comment]
it requires clang 3.8+, you must have something older, as `CXTranslationUnit_CreatePreambleOnFirstParse` was added in 3.8

**Comment by Danilodum** [comment]
you're completely right, thanks!

**Comment by joeroback** [comment]
np, let me know if it still does not work. i would be happy to help. working on the next release, which will hopefully fix a few known issues. and please file any issues you encounter. thanks!

**Comment by userkali** [comment]
Danilodum does this tool work with DS3?
